server:
  port: 9999
  servlet:
    session:
      timeout: 1800
    #上下文
#  servlet:
#    context-path: /thymeleaf

spring:
    #热部署配置
  devtools:
    restart:
        #设置开启热部署
      enabled: true
        #重启目录
      additional-paths: src/main/java

  datasource:
    url: jdbc:mysql://localhost:3306/base_user?serverTimezone=Hongkong&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwertyuiop123.

  #thymeleaf 配置
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false





moduleConfig:
  # 模块根目录
  rootPath: D:\E\ideaProject\module
  # 项目基础框架目录
  projectBasePath: D:\E\ideaProject\project
  # 生成项目的java代码中间路径
  javaMidPath: src\main\java\com
  # 生成项目的resources代码中间路径
  resourceMidPath: src\main\resources
